from abc import ABC, abstractmethod
import os
import httpx

class LLMProvider(ABC):
    @abstractmethod
    async def generate(self, prompt: str, system_prompt: str = "") -> str:
        pass

class OllamaProvider(LLMProvider):
    def __init__(self, base_url: str = None, model: str = None):
        self.base_url = base_url or os.getenv("LLM_BASE_URL", "http://localhost:11434")
        self.model = model or os.getenv("LLM_MODEL", "llama3")
        
    async def generate(self, prompt: str, system_prompt: str = "") -> str:
        try:
            async with httpx.AsyncClient() as client:
                response = await client.post(
                    f"{self.base_url}/api/generate",
                    json={
                        "model": self.model,
                        "prompt": prompt,
                        "system": system_prompt,
                        "stream": False
                    },
                    timeout=30.0
                )
                response.raise_for_status()
                data = response.json()
                return data.get("response", "")
        except Exception as e:
            print(f"Ollama generation error: {e}")
            return "I'm currently unable to connect to my generation backend to synthesize this answer."

# Factory
def get_llm_provider() -> LLMProvider:
    provider = os.getenv("LLM_PROVIDER", "ollama")
    if provider == "ollama":
        return OllamaProvider()
    
    # Fallback mock for testing without local LLM
    class MockProvider(LLMProvider):
        async def generate(self, prompt: str, system_prompt: str = "") -> str:
            return "This is a synthesized response generated by the LLM based on the retrieved documents."
            
    return MockProvider()
